PickadosGen/AdminView/AdminView/Controllers/TypeCompetiCalendarController.cs
using PickadosGenNHibernate.CEN.Pickados;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdminView.Controllers
{
    public class TypeCompetiCalendarController : Controller
    {
        // GET: TypeCompetiCalendar
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TypeCompetiCalendar(int idSport)
        {
            CompetitionCEN competis = new CompetitionCEN();
            SportCEN sports = new SportCEN();
            ViewBag.sport = sports.GetSportById(idSport);
            ViewBag.allCountries = competis.GetPlaces().ToList();
            return View();
        }
    }
}

PickadosGen/AdminView/AdminView/Views/TypeCompetiCalendar/TypeCompetiCalendar.cshtml
@using AdminView.Resources

<ul class="breadcrumb">
    <li>@Html.ActionLink(@textos.Calendar, "Calendar", "Calendar")</li>
    <li>@Html.ActionLink((string)ViewBag.sport.Name, "TypeCompetiCalendar", "TypeCompetiCalendar", new { idSport = ViewBag.sport.Id }, null)</li>
</ul>

<table class="table table-striped">
    <tr>
        <th>
            Type
        </th>
    </tr>
    <tr>
        <td>
            @Html.ActionLink(@textos.National, "CountryCalendar", "CountryCalendar", new { idSport = ViewBag.sport.Id, typeCompetition = "National" }, null)
        </td>
    </tr>
    <tr>
        <td>
            @Html.ActionLink(@textos.International, "CountryCalendar", "CountryCalendar", new { idSport = ViewBag.sport.Id, typeCompetition = "International" }, null)
        </td>
    </tr>
</table>