PickadosGen/AdminView/AdminView/Controllers/CountryCalendarController.cs
using PickadosGenNHibernate.CEN.Pickados;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdminView.Controllers
{
    public class CountryCalendarController : Controller
    {
        // GET: CountryCalendar
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CountryCalendar(int idSport = 0, string typeCompetition = "")
        {
            CompetitionCEN competis = new CompetitionCEN();
            SportCEN sports = new SportCEN();
            ViewBag.sport = sports.GetSportById(idSport);
            ViewBag.typeCompetition = typeCompetition;
            if (typeCompetition.Equals("National"))
            {
                ViewBag.allCountries = competis.GetClubPlaces().ToList();
            }
            else
            {
                ViewBag.allCountries = competis.GetNationalPlaces().ToList();
            }
            return View();
        }
    }
}

PickadosGen/AdminView/AdminView/Views/CountryCalendar/CountryCalendar.cshtml
@using AdminView.Resources

<ul class="breadcrumb">
    <li>@Html.ActionLink(@textos.Calendar, "Calendar", "Calendar")</li>
    <li>@Html.ActionLink((string)ViewBag.sport.Name, "TypeCompetiCalendar", "TypeCompetiCalendar", new { idSport = ViewBag.sport.Id }, null)</li>
    <li>@Html.ActionLink((string)ViewBag.typeCompetition, "CountryCalendar", "CountryCalendar", new { idSport = ViewBag.sport.Id, typeCompetition = ViewBag.typeCompetition }, null)</li>
</ul>

<table class="table table-striped">
    <tr>
        <th>
            @textos.Name
        </th>
    </tr>
    @foreach (var item in ViewBag.allCountries)
    {
        <tr>
            <td>
                @Html.ActionLink((string)item, "CompetiCalendar", "CompetiCalendar", new { countryName = item, idSport = ViewBag.sport.Id, typeCompetition = ViewBag.typeCompetition }, null)
            </td>
        </tr>
    }
</table>