PickadosGen/AdminView/AdminView/Controllers/MatchesController.cs
using PickadosGenNHibernate.CEN.Pickados;
using PickadosGenNHibernate.EN.Pickados;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdminView.Controllers
{
    public class MatchesController : Controller
    {
        // GET: Matches
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Matches(int idRound = 0, int idSeason = 0, int idCompetition = 0, string countryName = "", int idSport = 0, string typeCompetition = "")
        {
            CompetitionCEN competis = new CompetitionCEN();
            SportCEN sports = new SportCEN();
            SeasonCEN seasons = new SeasonCEN();
            RoundCEN rounds = new RoundCEN();
            Event_CEN events = new Event_CEN();
            CompetitionEN com = competis.GetCompetitionById(idCompetition);
            List<Event_EN> allEvents = events.GetEventsByRoundAndCompetition(idRound, idCompetition).ToList();
            List<MatchEN> allMatches = new List<MatchEN>();
            MatchCEN matches = new MatchCEN();
            ViewBag.country = countryName;
            ViewBag.sport = sports.GetSportById(idSport);
            ViewBag.competition = competis.GetCompetitionById(idCompetition);
            ViewBag.season = seasons.GetSeasonByID(idSeason);
            ViewBag.typeCompetition = typeCompetition;
            ViewBag.round = rounds.ReadOID(idRound);
            foreach (Event_EN oneEv in allEvents)
            {
                allMatches.Add(matches.GetMatchById(oneEv.Id));
            }
            ViewBag.totalMatches = allMatches;
            return View();
        }

        public ActionResult Edit(int idMatch = 0, int idRound = 0, int idSeason = 0, int idCompetition = 0, string countryName = "", int idSport = 0, string typeCompetition = "")
        {
            MatchCEN matches = new MatchCEN();
            ViewBag.country = countryName;
            ViewBag.sport = idSport;
            ViewBag.competition = idCompetition;
            ViewBag.season = idSeason;
            ViewBag.typeCompetition = typeCompetition;
            ViewBag.round = idRound;
            MatchEN match = matches.GetMatchById(idMatch);
            return View(match);
        }

        [HttpPost]
        public ActionResult Edit(int idRound, int idSeason, int idCompetition, string countryName, int idSport, string typeCompetition, int id, FormCollection collection)
        {
            MatchCEN matches = new MatchCEN();
            MatchEN matchEdited = new MatchEN();
            matchEdited.Id = id;
            matchEdited.Stadium = collection["Stadium"].ToString();
            matchEdited.Date = DateTime.Parse(collection["Date"].ToString());
            matches.ModifyMatch(matchEdited.Id, matchEdited.Date, matchEdited.Stadium);
            return RedirectToAction("Matches", "Matches", new { idRound = idRound, idSeason = idSeason, idCompetition = idCompetition, countryName = countryName, idSport = idSport, typeCompetition = typeCompetition });
        }

        public JsonResult AutoComplete(string prefix, string typeCompetition)
        {
            TeamCEN entities = new TeamCEN();
            List<TeamEN> total = new List<TeamEN>();
            if (typeCompetition.Equals("National"))
            {
                total = entities.GetNationalTeams().ToList();
            }
            else
            {
                total = entities.GetInternationalTeam().ToList();
            }
            var teams = (from team in total
                         where team.Name.Contains(prefix)
                         select new
                         {
                             label = team.Name,
                             val = team.Id
                         }).ToList();

            return Json(teams);
        }

        [HttpPost]
        public ActionResult AddLocalTeamToMatch(string teamNameLocal, string teamIdLocal, int idLocalTeam, int idMatch, int idRound, int idSeason, int idCompetition, string countryName, int idSport, string typeCompetition)
        {
            MatchCEN matches = new MatchCEN();
            matches.UnjoinLocalTeamToMatch(idMatch, idLocalTeam);
            matches.AddLocalTeamToMatch(idMatch, Convert.ToInt32(teamIdLocal));
            return RedirectToAction("Matches", "Matches", new { idRound = idRound, idSeason = idSeason, idCompetition = idCompetition, countryName = countryName, idSport = idSport, typeCompetition = typeCompetition });
        }

        [HttpPost]
        public ActionResult AddAwayTeamToMatch(string teamNameAway, string teamIdAway, int idAwayTeam, int idMatch, int idRound, int idSeason, int idCompetition, string countryName, int idSport, string typeCompetition)
        {
            MatchCEN matches = new MatchCEN();
            matches.UnjoinAwayTeamToMatch(idMatch, idAwayTeam);
            matches.AddAwayTeamToMatch(idMatch, Convert.ToInt32(teamIdAway));
            return RedirectToAction("Matches", "Matches", new { idRound = idRound, idSeason = idSeason, idCompetition = idCompetition, countryName = countryName, idSport = idSport, typeCompetition = typeCompetition });
        }
    }
}

PickadosGen/AdminView/AdminView/Controllers/RoundController.cs
using PickadosGenNHibernate.CEN.Pickados;
using PickadosGenNHibernate.EN.Pickados;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdminView.Controllers
{
    public class RoundController : Controller
    {
        // GET: Round
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Round(int idSeason = 0, int idCompetition = 0, string countryName = "", int idSport = 0, string typeCompetition = "")
        {
            CompetitionCEN competis = new CompetitionCEN();
            SportCEN sports = new SportCEN();
            SeasonCEN seasons = new SeasonCEN();
            RoundCEN rounds = new RoundCEN();
            ViewBag.country = countryName;
            ViewBag.sport = sports.GetSportById(idSport);
            ViewBag.competition = competis.GetCompetitionById(idCompetition);
            SeasonEN season = seasons.GetSeasonByID(idSeason);
            ViewBag.season = season;
            ViewBag.allRounds = rounds.GetRoundBySeason(idSeason).ToList();
            ViewBag.typeCompetition = typeCompetition;
            return View();
        }
    }
}

PickadosGen/AdminView/AdminView/Controllers/SeasonsController.cs
using PickadosGenNHibernate.CEN.Pickados;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdminView.Controllers
{
    public class SeasonsController : Controller
    {
        // GET: Seasons
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Seasons(int idCompetition = 0, string countryName = "", int idSport = 0, string typeCompetition = "")
        {
            CompetitionCEN competis = new CompetitionCEN();
            SportCEN sports = new SportCEN();
            SeasonCEN seasons = new SeasonCEN();
            ViewBag.country = countryName;
            ViewBag.sport = sports.GetSportById(idSport);
            ViewBag.competition = competis.GetCompetitionById(idCompetition);
            ViewBag.allSeasons = seasons.GetSeasonByCompetition(idCompetition).ToList();
            ViewBag.typeCompetition = typeCompetition;
            return View();
        }
    }
}

PickadosGen/AdminView/AdminView/Views/Matches/Edit.cshtml
@using AdminView.Resources

@model PickadosGenNHibernate.EN.Pickados.MatchEN

<h1>@textos.Match</h1>
<hr />

<div class="col-xs-6 col-md-6 text-center">
    <strong>@textos.Local</strong><br />
    @using (Html.BeginForm("AddLocalTeamToMatch", "Matches", routeValues: new { idLocalTeam = Model.Home.Id, idMatch = Model.Id, idRound = ViewBag.round, idSeason = ViewBag.season, idCompetition = ViewBag.competition, countryName = ViewBag.country, idSport = ViewBag.sport, typeCompetition = ViewBag.typeCompetition }))
    {
        <input type="hidden" id="hfTeamLocal" name="TeamIdLocal" />
        <div class="input-group">
            <input type="text" id="txtTeamLocal" name="TeamNameLocal" value="@Model.Home.Name" class="form-control" />
            <span class="input-group-btn"><button type="submit" class="btn btn-default">Añadir</button></span>
        </div>
    }
</div>

<div class="col-xs-6 col-md-6 text-center">
    <strong>@textos.Visitor</strong><br />
    @using (Html.BeginForm("AddAwayTeamToMatch", "Matches", routeValues: new { idAwayTeam = Model.Away.Id, idMatch = Model.Id, idRound = ViewBag.round, idSeason = ViewBag.season, idCompetition = ViewBag.competition, countryName = ViewBag.country, idSport = ViewBag.sport, typeCompetition = ViewBag.typeCompetition }))
    {
        <input type="hidden" id="hfTeamAway" name="TeamIdAway" />
        <div class="input-group">
            <input type="text" id="txtTeamAway" name="TeamNameAway" value="@Model.Away.Name" class="form-control" />
            <span class="input-group-btn"><button type="submit" class="btn btn-default">Añadir</button></span>
        </div>
    }
</div>

@using (Html.BeginForm("Edit", "Matches", routeValues: new { idRound = ViewBag.round, idSeason = ViewBag.season, idCompetition = ViewBag.competition, countryName = ViewBag.country, idSport = ViewBag.sport, typeCompetition = ViewBag.typeCompetition }))
{
    //@Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stadium, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stadium, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stadium, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@textos.Save class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink(@textos.Back, "Matches", "Matches", new { idRound = ViewBag.round, idSeason=ViewBag.season, idCompetition = ViewBag.competition, countryName = ViewBag.country, idSport = ViewBag.sport, typeCompetition = ViewBag.typeCompetition }, null)
</div>

<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.0.min.js" type="text/javascript"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/jquery-ui.min.js" type="text/javascript"></script>
<link href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/themes/blitzer/jquery-ui.css"
      rel="Stylesheet" type="text/css" />
<script type="text/javascript">
        $(function () {
            $("#txtTeamLocal").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: '/Teams/AutoComplete/',
                        data: "{ 'prefix': '" + request.term + "', 'typeCompetition': '@ViewBag.typeCompetition'}",
                        dataType: "json",
                        type: "POST",
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            response($.map(data, function (item) {
                                return item;
                            }))
                        },
                        error: function (response) {
                            alert(response.responseText);
                        },
                        failure: function (response) {
                            alert(response.responseText);
                        }
                    });
                },
                select: function (e, i) {
                    $("#hfTeamLocal").val(i.item.val);
                },
                minLength: 1
            });
        });

    $(function () {
        $("#txtTeamAway").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: '/Teams/AutoComplete/',
                    data: "{ 'prefix': '" + request.term + "', 'typeCompetition': '@ViewBag.typeCompetition'}",
                    dataType: "json",
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        response($.map(data, function (item) {
                            return item;
                        }))
                    },
                    error: function (response) {
                        alert(response.responseText);
                    },
                    failure: function (response) {
                        alert(response.responseText);
                    }
                });
            },
            select: function (e, i) {
                $("#hfTeamAway").val(i.item.val);
            },
            minLength: 1
        });
    });
</script>

PickadosGen/AdminView/AdminView/Views/Matches/Matches.cshtml
@using AdminView.Resources

@helper TempName(string message, DateTime init, DateTime fin)
{
string inicio = init.Year.ToString();
string final = fin.Year.ToString();
string total = inicio + "/" + final;
    @Html.Raw(message + total);
}

<ul class="breadcrumb">
    <li>@Html.ActionLink(@textos.Calendar, "Calendar", "Calendar")</li>
    <li>@Html.ActionLink((string)ViewBag.typeCompetition, "TypeCompetiCalendar", "TypeCompetiCalendar", new { idSport = ViewBag.sport.Id }, null)</li>
    <li>@Html.ActionLink((string)ViewBag.sport.Name, "CountryCalendar", "CountryCalendar", new { idSport = ViewBag.sport.Id, typeCompetition = ViewBag.typeCompetition }, null)</li>
    <li>@Html.ActionLink((string)ViewBag.country, "CompetiCalendar", "CompetiCalendar", new { countryName = ViewBag.country, idSport = ViewBag.sport.Id, typeCompetition = ViewBag.typeCompetition }, null)</li>
    <li>@Html.ActionLink((string)ViewBag.competition.Name, "Seasons", "Seasons", new { idCompetition = ViewBag.competition.Id, countryName = ViewBag.country, idSport = ViewBag.sport.Id, typeCompetition = ViewBag.typeCompetition }, null)</li>
    <li>@Html.ActionLink((string)@TempName(ViewBag.Message, ViewBag.season.InitDate, ViewBag.season.FinalDate).ToString(), "Round", "Round", new { idSeason = ViewBag.season.Id, idCompetition = ViewBag.competition.Id, countryName = ViewBag.country, idSport = ViewBag.sport.Id, typeCompetition = ViewBag.typeCompetition }, null)</li>
    <li>@Html.ActionLink((string)ViewBag.round.Name, "Matches", "Matches", new { idRound = ViewBag.round.Id, idSeason = ViewBag.season.Id, idCompetition = ViewBag.competition.Id, countryName = ViewBag.country, idSport = ViewBag.sport.Id, typeCompetition = ViewBag.typeCompetition }, null)</li>
</ul>

@foreach (var item in ViewBag.totalMatches)
{
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-primary">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-xs-3 col-md-3 text-center">
                                <strong>@textos.Local</strong><br />
                                @item.Home.Name
                            </div>
                            <div class="col-xs-5 col-md-5 text-center">
                                <strong>@textos.Information</strong><br />
                                <strong>@textos.Stadium</strong> @item.Stadium<br />
                                <strong>@textos.Date</strong><br />
                                @item.Date <br />
                                <strong>@textos.State</strong> <br />
                                Pendiente
                            </div>
                            <div class="col-xs-3 col-md-3 text-center">
                                <strong>@textos.Visitor</strong><br />
                                @item.Away.Name
                            </div>
                        </div>
                        <a href="@Url.Action("Edit", "Matches", new { idMatch = item.Id, idRound = ViewBag.round.Id, idSeason = ViewBag.season.Id, idCompetition = ViewBag.competition.Id, countryName = ViewBag.country, idSport = ViewBag.sport.Id, typeCompetition = ViewBag.typeCompetition })" class="fa fa-pencil fa-fw"></a>
                        <!--<a href="http://www.jquery2dotnet.com/" class="btn btn-success btn-lg btn-block" role="button"><span class="glyphicon glyphicon-globe"></span> Website</a>-->
                    </div>
                </div>
            </div>
        </div>
    </div>
}

PickadosGen/AdminView/AdminView/Views/Matches/getMatches.cshtml
<table class="table table-striped">
    <tr>
        <th>
            Name
        </th>
    </tr>
    @foreach (var item in ViewBag.allSports)
    {
        <tr>
            <td>
                ViewBag.totalMatches.Home.Name
            </td>
        </tr>
    }
</table>