PickadosGen/AdminView/AdminView/Controllers/CountryController.cs
using PickadosGenNHibernate.CEN.Pickados;
using PickadosGenNHibernate.EN.Pickados;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdminView.Controllers
{
    public class CountryController : Controller
    {
        // GET: Country
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Country(int idSport = 0, string typeCompetition="")
        {
            CompetitionCEN competis = new CompetitionCEN();
            SportCEN sports = new SportCEN();
            ViewBag.sport = sports.GetSportById(idSport);
            ViewBag.typeCompetition = typeCompetition;
            if (typeCompetition.Equals("National")) {
                ViewBag.allCountries = competis.GetClubPlaces().ToList();
            } else
            {
                ViewBag.allCountries = competis.GetNationalPlaces().ToList();
            }
            return View();
        }
    }
}

PickadosGen/AdminView/AdminView/Controllers/TypeCompetitionController.cs
using PickadosGenNHibernate.CEN.Pickados;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdminView.Controllers
{
    public class TypeCompetitionController : Controller
    {
        // GET: TypeCompetition
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TypeCompetition(int idSport = 0)
        {
            CompetitionCEN competis = new CompetitionCEN();
            SportCEN sports = new SportCEN();
            ViewBag.sport = sports.GetSportById(idSport);
            ViewBag.allCountries = competis.GetPlaces().ToList();
            return View();
        }
    }
}

PickadosGen/AdminView/AdminView/Views/TypeCompetition/TypeCompetition.cshtml
@using AdminView.Resources

<ul class="breadcrumb">
    <li>@Html.ActionLink(@textos.Sport, "Sports", "Sports")</li>
    <li>@Html.ActionLink((string)ViewBag.sport.Name, "TypeCompetition", "TypeCompetition", new { idSport = ViewBag.sport.Id }, null)</li>
</ul>

<table class="table table-striped">
    <tr>
        <th>
            Type
        </th>
    </tr>
    <tr>
        <td>
            @Html.ActionLink(@textos.National, "Country", "Country", new { idSport = ViewBag.sport.Id, typeCompetition = "National" }, null)
        </td>
    </tr>
    <tr>
        <td>
            @Html.ActionLink(@textos.International, "Country", "Country", new { idSport = ViewBag.sport.Id, typeCompetition="International" }, null)
        </td>
    </tr>
</table>